### ISSUE TITLE
ImportError: cannot import name 'extract_pdf_text' from 'utils.config'

### ISSUE THREAD

**Issue by bssayla** [AnasAber/NLP_Recruitment#2]
the extract_pdf_text function doesn't exist https://github.com/AnasAber/NLP_Recruitment/blob/8edfe634cfab7d14e7b3558aba1039e0e6270c47/src/app.py#L4

is there any specific reason why it got commented in the config file https://github.com/AnasAber/NLP_Recruitment/blob/8edfe634cfab7d14e7b3558aba1039e0e6270c47/src/utils/config.py#L20-L39

should i just remove it ?

**Comment by AnasAber** [comment]
Yup just go ahead, was testing different functions, the used one is the one that works well!

**Comment by bssayla** [comment]
ok i'll work on cleaning the code
