### ISSUE TITLE
Groq API Usage 

### ISSUE THREAD

**Issue by bssayla** [AnasAber/NLP_Recruitment#3]
Is there any instruction i should do to use the qrog api because i get this error when i try to run the app
> [!CAUTION]
ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1174fca10>: Failed to establish a new connection: [Errno 61] Connection refused'))

how do run the this localhost url
https://github.com/AnasAber/NLP_Recruitment/blob/8edfe634cfab7d14e7b3558aba1039e0e6270c47/src/app.py#L8
is it supposed to be the streamlit app url or somthing?

**Comment by AnasAber** [comment]
It's just flask api, you should run two things:
- streamlit run app.py
- py main_reasoning.py

The error should go away if you ran main_reasoning.py

**Comment by bssayla** [comment]
ok all clear
