### ISSUE TITLE
KeyError: 'response'

### ISSUE THREAD

**Issue by bssayla** [AnasAber/NLP_Recruitment#4]
# Description
when i upload a pdf resume 1st before adding a job description it give an error 

<img width="734" alt="Screenshot 2024-09-06 at 20 24 16" src="https://github.com/user-attachments/assets/ce0c6e25-52b3-4bfa-a029-7dadeea59d1d">

# Solution
As a proposed solution we can add a button to press when the user give all the inputs to make it easier to use

**Comment by AnasAber** [comment]
Exactly my thoughts, still not focusing on the UI part that's why :>

**Comment by bssayla** [comment]
you can assign it to me i'll work on it
